name: Makefile CI

on:
  push:
    branches: [ "version-2" ]
  pull_request:
    branches: [ "version-2", "version2-sdk-upgrade" ]

env:
  CIQ_SDK_VERSION: 6.2.0

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate a developer key
        run: |
          openssl genrsa -out developer_key.pem 4096
          openssl pkcs8 -topk8 -inform PEM -outform DER -in developer_key.pem -out developer_key.der -nocrypt

      - name: Install ConnectIQ SDK
        run: |
          curl -s https://raw.githubusercontent.com/lindell/connect-iq-sdk-manager-cli/master/install.sh | sh
          /usr/local/bin/connect-iq-sdk-manager agreement view
#          echo $CIQ_SDK_URL
#          curl -s -L "${CIQ_SDK_URL}" -o $HOME/connectiq-sdk-lin-${CIQ_SDK_VERSION}.zip
#          mkdir -p /opt/connectiq-sdk-lin-${CIQ_SDK_VERSION}
#          cd /opt/connectiq-sdk-lin-${CIQ_SDK_VERSION}
#          unzip -q $HOME/connectiq-sdk-lin-${CIQ_SDK_VERSION}.zip
#          chmod -R go-w /opt/connectiq-sdk-lin-${CIQ_SDK_VERSION}
#          echo ls -la /opt/connectiq-sdk-lin-${CIQ_SDK_VERSION}

      - name: Create properties.mk
        run: |
          touch properties.mk
          echo "SDK_HOME = /opt/connectiq-sdk-lin-${CIQ_SDK_VERSION}" >> properties.mk
          echo "DEVELOPER_KEY = `pwd`/developer_key.der" >> properties.mk
          echo "cat properties.mk"
          cat properties.mk

      - name: Build
        run: make package
