name: Makefile CI

on:
  push:
    branches: [ "version-2" ]
  pull_request:
    branches: [ "version-2", "version2-sdk-upgrade" ]

env:
  #  CIQ_SDK_MANAGER_DIR_URL: https://developer.garmin.com/downloads/connect-iq/sdk-manager
  #  CIQ_SDK_MANAGER_LIST_URL: https://developer.garmin.com/downloads/connect-iq/sdk-manager/sdk-manager.json
  CIQ_SDK_MANAGER_SDK_DIR_URL: https://developer.garmin.com/downloads/connect-iq/sdks/
  CIQ_SDK_MANAGER_SDK_LIST: sdks.json
  CIQ_SDK: connectiq-sdk-lin-6.2.0-2023-05-26-cc5fddb5d.zip
  CIQ_SDK_VERSION: 6.2.0

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate a developer key
        run: |
          openssl genrsa -out developer_key.pem 4096
          openssl pkcs8 -topk8 -inform PEM -outform DER -in developer_key.pem -out developer_key.der -nocrypt

      - name: Downloads ConnectIQ SDK
        run: |
          CIQ_SDK_URL=${CIQ_SDK_MANAGER_SDK_DIR_URL}${CIQ_SDK}
          echo $CIQ_SDK_URL
          curl -s -L "${CIQ_SDK_URL}" -o $HOME/connectiq-sdk-lin-${CIQ_SDK_VERSION}.zip
          mkdir -p /opt/connectiq-sdk-lin-${CIQ_SDK_VERSION}
          cd /opt/connectiq-sdk-lin-${CIQ_SDK_VERSION}
          unzip -q $HOME/connectiq-sdk-lin-${CIQ_SDK_VERSION}.zip
          chmod -R go-w /opt/connectiq-sdk-lin-${CIQ_SDK_VERSION}
          echo ls -la /opt/connectiq-sdk-lin-${CIQ_SDK_VERSION}

      - name: Create properties.mk
        run: |
          touch properties.mk
          echo "SDK_HOME = /opt/connectiq-sdk-lin-${CIQ_SDK_VERSION}" >> properties.mk
          echo "DEVELOPER_KEY = `pwd`/developer_key" >> properties.mk
          echo "cat properties.mk"
          cat properties.mk

      - name: Build
        run: make package
